### ISSUE TITLE
fails for credential helper

### ISSUE THREAD

**Issue by lmmarsano** [hashicorp/tfc-getting-started#20]
The setup script seems to expect credentials stored in cleartext.
```shellsession
$ ./scripts/setup.sh
jq: error: Could not open file /home/luism/.terraform.d/credentials.tfrc.json: No such file or directory
$ cat ~/.terraformrc
credentials_helper "keychain" {}
```

**Comment by p0onage** [comment]
I'm getting the same issue

**Comment by p0onage** [comment]
https://github.com/hashicorp/tfc-getting-started/pull/22

**Comment by barrettclark** [comment]
We recommend that you run `terraform login` from the command line (https://github.com/hashicorp/tfc-getting-started#1-log-in-to-terraform-cloud-via-the-cli), which creates the file `~/.terraform.d/credentials.tfrc.json` with the token that you create through the login process.
