### ISSUE TITLE
setup script parse error

### ISSUE THREAD

**Issue by kajatiger** [hashicorp/tfc-getting-started#24]
When I run 
```bash 
./scripts/setup.sh
```
I get
```bash
parse error: Invalid numeric literal at line 1, column 10
```

**Comment by laurenolivia** [comment]
@kajatiger Thanks for raising this issue. Can you confirm that you changed into the directory via: `cd tfc-getting-started` and then ran the script `./scripts/setup.sh`?

**Comment by kajatiger** [comment]
> Can you confirm whether creating organizations is disabled for non-admins?

I don't know what this means. Creating organizations where? 
The setup script is already failing at the version check. I just tried the commands out separately and I am getting the same error. 
For example [this line](https://github.com/hashicorp/tfc-getting-started/blob/62b6206eb03bdd41dd3fa1e203cda1110ea7ccaf/scripts/setup.sh#L56) in the script raises it:
```
installedTerraformMajorVersion=$(terraform version -json | jq -r '.terraform_version' | cut -d '.' -f 1)
```
And I am wondering where exactly this comes from... There is a similar issue decribed here: https://stackoverflow.com/questions/67889924/parse-error-invalid-numeric-literal-at-line-1-column-10

It seems to be a problem in the `jq` query. Maybe the return value of the terraform version is not the expected format?

**Comment by laurenolivia** [comment]
Creating an organization in your TFC account. This might be jumping too far ahead.

Let's start by gathering more context:

Have you [downloaded](https://learn.hashicorp.com/tutorials/terraform/install-cli) Terraform?
What version is returned in the CLI when you run `terraform -version`?
Have you created an account in Terraform Cloud?

**Comment by kajatiger** [comment]
I have downloaded terraform. I had an older version and updated it now.
The version returns
```
Terraform v1.2.8
on darwin_amd64
```
And I do have a terrraform account in the cloud.
And this time the setup script seems to work, so I guess the version was the problem.
