### ISSUE TITLE
backend.tf still uses remote backend instead of cloud integration

### ISSUE THREAD

**Issue by alexmills802** [hashicorp/tfc-getting-started#33]
Hashicorp has recommended using the cloud integration since Terraform 1.1.0 as per the note at the top of this page: https://developer.hashicorp.com/terraform/language/settings/backends/remote

Is there any good reason that this repo still uses the remote backend? Should I submit a PR with an update?

**Comment by annawinkler** [comment]
👋 Hi @alexmills802 - thank you for raising this issue. No, I don't think there is a good reason that we're using the remote backend, and cloud makes sense to me. If you have a PR with an update that would be appreciated! 💖 Thank you!
